Defined Sn as a HIT
vikraman/2DTypes pull request #32
Opened 2021-01-02 00:31 UTC by vikraman

Fixes #8

2021-01-03 16:43 UTC, inexxt commented
I wouldn't say I undestand the whole code, but - why is it not parametrised by `n`?
(Such as the relation we've defined in here https://github.com/vikraman/2DTypes/commit/b6b6c35c255622294397bb188c14e579a1a88629 ?)

2021-01-05 22:29 UTC, inexxt commented
I changed the code to be parametrised by `n` (e.g. in Fin n instead of ℕ) - jus to show what I meant, not as a final statement. Please modify it as you like.

2021-01-05 22:31 UTC, inexxt requested changes

2021-01-05 22:31 UTC, inexxt commented on Pi+/Coxeter/CoxeterHIT.agda
> +-- _++_ {m} = CListRec.f (λ w → w) (λ n f w → n :: f w) (λ= λ _ → cancel) (λ p → λ= λ _ → swap p) (λ= λ _ → braid)
I don't really understand how to deal with HITs in Agda, so just commented these out.

2021-01-05 22:54 UTC, inexxt commented on Pi+/Coxeter/CoxeterHIT.agda
> +-- _++_ {m} = CListRec.f (λ w → w) (λ n f w → n :: f w) (λ= λ _ → cancel) (λ p → λ= λ _ → swap p) (λ= λ _ → braid)
Fixed.

2021-01-06 12:43 UTC, vikraman commented
Wouldn't it be better to just expand out the `Fin`s like in `LL` ?

2021-01-06 14:06 UTC, inexxt approved these changes

2021-01-06 14:16 UTC, merged